### ISSUE TITLE
ApkScanner not launching on Windows with russian localization

### ISSUE THREAD

**Issue by Lebsasha** [apk-spectrum/apk-scanner#3]
When I try to launch ApkScanner double clicking on it, nothing is appearing. If I launch application via Terminal, it shows following error:
``` 
Exception in thread "main" java.lang.IllegalArgumentException: 
No enum constant com.apkscanner.resource.RFile.RAW_STRINGS_RU
        at java.lang.Enum.valueOf(Unknown Source)
        at com.apkscanner.resource.RFile.valueOf(RFile.java:1)
        at com.apkscanner.resource.RStr.makeStringXmlPath(RStr.java:444)
        at com.apkscanner.resource.RStr.setLanguage(RStr.java:425)
        at com.apkscanner.Main.main(Main.java:34)
```
I could guess that program tries to automatically determine language and load appropriate localization, but it is failing to do this for Russian language.

**Comment by sunggyu-kam** [comment]
Hello.
From the logs, it seems to be version 2.9.
The installation file for version 2.10 has not been uploaded yet.
If it is possible to build, is it possible to check the operation by building the 2.10 version?
Version 2.10 or 2.11 will be uploaded soon.

**Comment by Lebsasha** [comment]
Unfortunately, I don't have time to build the application today, but I'll try to do it one of next days

**Comment by Lebsasha** [comment]
I fetch all commits for current moment from master, successfully build application (running `mvnw.cmd package`) and could launch it without problems. 
However, if I checkout v2.10_r1 tag and try to build, maven complains `[FATAL] Non-resolvable parent POM for com.apkspectrum:scanner:2.10.0-SNAPSHOT: Could not find artifact com.apkspectrum:core:pom:2.10.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 13` and doesn't want build the application.
So initial v2.10 version is not building, but the latest version of the app does and it doesn't crash anymore.
Thank you!

**Comment by sunggyu-kam** [comment]
@Lebsasha,  Thank you very much for confirming.
